swagger: "2.0"
info:
  title: "echo"
  version: "v1"
paths:
  /v1/echo:
    post:
      summary: "An echoing endpoint"
      operationId: "Echo"
      parameters:
        - in: body
          name: echoRequest
          required: true
          schema:
            $ref: "#/definitions/EchoRequest"
      responses:
        200:
          description: "An echo"
          schema:
            $ref: "#/definitions/EchoReply"
        default:
          description: "An error"
          schema:
            $ref: "#/definitions/ErrorReply"
definitions:
  EchoRequest:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  EchoReply:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  ErrorReply:
    type: object
    required:
      - code
      - message
    properties:
      message:
        type: string
      code:
        type: string
