// Code generated by go-swagger; DO NOT EDIT.

// Package restapi echo
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: v1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
