// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "echo",
    "version": "v1"
  },
  "paths": {
    "/v1/echo": {
      "post": {
        "summary": "An echoing endpoint",
        "operationId": "Echo",
        "parameters": [
          {
            "name": "echoRequest",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EchoRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "An echo",
            "schema": {
              "$ref": "#/definitions/EchoReply"
            }
          },
          "default": {
            "description": "An error",
            "schema": {
              "$ref": "#/definitions/ErrorReply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "EchoReply": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "EchoRequest": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ErrorReply": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "echo",
    "version": "v1"
  },
  "paths": {
    "/v1/echo": {
      "post": {
        "summary": "An echoing endpoint",
        "operationId": "Echo",
        "parameters": [
          {
            "name": "echoRequest",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EchoRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "An echo",
            "schema": {
              "$ref": "#/definitions/EchoReply"
            }
          },
          "default": {
            "description": "An error",
            "schema": {
              "$ref": "#/definitions/ErrorReply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "EchoReply": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "EchoRequest": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ErrorReply": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
